### ISSUE TITLE
可以开放header自定义接口吗，例如addHeader

### ISSUE THREAD

**Issue by PureDark** [qstumn/FastImageSize#1]
因为有些网站的图片，必须有referer才能加载，不然就是404或者防盗链图片

虽然现在可以通过提供自定义的 InputStreamProvider 来实现，但是这个也应该算比较基础的需求了，直接提供一个方法比较好

**Comment by qstumn** [comment]
感谢您的建议，因为考虑到实际上大家都有各自的网络库，就比如现在OKHttp几乎都已经成标配了，如果直接添加addHeader就只有和HttpUrlConnection配合，会过于耦合了，所以才提供了InputStreamProvider ，让FastImageSize只专心于解析图片尺寸。
